#!/bin/bash

# dependencies: curl, jq (https://stedolan.github.io/jq/)

# example usage: cf_unban_all

# append cloudflare email address and API token:
CF_API_KEY="${CF_API_KEY:-}"
CF_API_EMAIL="${CF_API_EMAIL:-}"

if [ -z ${CF_API_KEY+x} ]; then
    echo "env var CF_API_KEY not set"
    exit 1
fi
if [ -z ${CF_API_EMAIL+x} ]; then
    echo "env var CF_API_EMAIL not set"
    exit 1
fi

CONTENT="-"
while [ ! -z "$CONTENT" ]; do
    CONTENT=$(curl -sSX GET "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?mode=block&configuration_target=ip" -H "X-Auth-Email: $CF_API_EMAIL" -H "X-Auth-Key: $CF_API_KEY" -H "Content-Type: application/json" | jq -r '.result[].id')
    for id in $CONTENT; do
        curl -sSX DELETE "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/$id" -H "X-Auth-Email: $CF_API_EMAIL" -H "X-Auth-Key: $CF_API_KEY" -H "Content-Type: application/json"
    done
done
